# Generated by Django 5.0.7 on 2024-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img/User_Default.jpg', upload_to='images/'),
        ),
    ]
